CREATE TABLE [dbo].[Games] (
    [Id] INT NOT NULL PRIMARY KEY, 
    [Title] TEXT NOT NULL, 
    [Platform] TEXT NULL, 
    [Status] TEXT NULL, 
    [Rating] INT NULL, 
    [TimePlayed] TEXT NULL, 
    [Seconds] INT NOT NULL,
    [Obtained] DATETIME NULL,
	[Started] DATETIME NULL,
	[LastPlayed] DATETIME NULL,
	[Notes] TEXT NULL,
	[URLs] TEXT NULL,
	[Filters] TEXT NULL,
	[Developers] TEXT NULL,
	[Publishers] TEXT NULL,
	[ReleaseDate] TEXT NULL,
	[Genre] TEXT NULL,
	[PlayerCount] TEXT NULL,
	[Price] DECIMAL NULL,
	[GameDesc] TEXT NULL,
	[Launch] TEXT NULL,
	[Blur] TEXT NOT NULL,
	[Overlay] TEXT NOT NULL
);

